// src/modules/ledger/ledger.types.ts
import { InvoiceStatus } from '../../types/prisma';

export interface CreateLedgerInput {
  name: string;
}

export interface UpdateLedgerInput {
  name: string;
}

export interface CreateJournalLineInput {
  ledgerId: string;
  debit?: number;
  credit?: number;
}

export interface CreateJournalEntryInput {
  invoiceId: string;
  entryDate: string;
  description?: string;
  lines: CreateJournalLineInput[];
}

export interface LedgerFilters {
  search?: string;
  page?: number;
  limit?: number;
}

export interface JournalEntryFilters {
  invoiceId?: string;
  dateFrom?: string;
  dateTo?: string;
  page?: number;
  limit?: number;
}

export interface LedgerResponse {
  id: string;
  name: string;
  organizationId: string;
  createdAt: Date;
  _count: {
    journalLines: number;
  };
}

export interface JournalLineResponse {
  id: string;
  ledgerId: string;
  ledger: {
    id: string;
    name: string;
  };
  debit: string | null;
  credit: string | null;
}

export interface LedgerDetailResponse extends LedgerResponse {
  journalLines: JournalLineResponse[];
  totalDebit: string;
  totalCredit: string;
}

export interface JournalEntryResponse {
  id: string;
  invoiceId: string;
  invoice: {
    id: string;
    invoiceNumber: string;
    totalAmount: string;
    status: InvoiceStatus;
  };
  entryDate: Date;
  description: string | null;
  isAutoGenerated: boolean;
  lines: JournalLineResponse[];
  totalDebit: string;
  totalCredit: string;
  isBalanced: boolean;
  createdAt: Date;
}

export interface LedgerBalanceSummary {
  ledgerId: string;
  ledgerName: string;
  totalDebit: string;
  totalCredit: string;
  netBalance: string;
}
