// src/modules/ledger/ledger.service.ts
import { ledgerRepository, LedgerWithCount, LedgerWithLines, JournalEntryWithAll } from './ledger.repository';
import { invoicesRepository, InvoiceWithAll } from '../invoices/invoices.repository';
import { logger } from '../../common/logger/logger';
import {
  CreateLedgerInput,
  UpdateLedgerInput,
  CreateJournalEntryInput,
  CreateJournalLineInput,
  LedgerFilters,
  JournalEntryFilters,
  LedgerResponse,
  LedgerDetailResponse,
  JournalEntryResponse,
  JournalLineResponse,
  LedgerBalanceSummary
} from './ledger.types';
import { PaginatedResponse } from '../../shared/types';
import { NotFoundError, ConflictError, UnprocessableError } from '../../errors';
import { InvoiceStatus } from '../../types/prisma';

const DEFAULT_LEDGER_NAMES = [
  'Purchase Account',
  'Sales Account',
  'Input GST - CGST',
  'Input GST - SGST',
  'Input GST - IGST',
  'Output GST - CGST',
  'Output GST - SGST',
  'Output GST - IGST',
  'Accounts Payable',
  'Accounts Receivable',
  'Bank',
  'Cash',
] as const;

const LOW_BALANCE_TOLERANCE = 0.01;

export class LedgerService {
  private calculateTotals(lines: CreateJournalLineInput[]): { totalDebit: number; totalCredit: number; isBalanced: boolean } {
    const totalDebit = lines.reduce((sum, line) => sum + (line.debit || 0), 0);
    const totalCredit = lines.reduce((sum, line) => sum + (line.credit || 0), 0);
    const isBalanced = Math.abs(totalDebit - totalCredit) <= LOW_BALANCE_TOLERANCE;
    return { totalDebit, totalCredit, isBalanced };
  }

  private mapToJournalEntryResponse(entry: JournalEntryWithAll): JournalEntryResponse {
    const totalDebit = entry.lines.reduce((sum: number, line: any) => sum + parseFloat(line.debit?.toString() || '0'), 0);
    const totalCredit = entry.lines.reduce((sum: number, line: any) => sum + parseFloat(line.credit?.toString() || '0'), 0);
    const isBalanced = Math.abs(totalDebit - totalCredit) <= LOW_BALANCE_TOLERANCE;

    return {
      id: entry.id,
      invoiceId: entry.invoiceId,
      invoice: {
        id: entry.invoice.id,
        invoiceNumber: entry.invoice.invoiceNumber,
        totalAmount: entry.invoice.totalAmount.toString(),
        status: entry.invoice.status
      },
      entryDate: entry.entryDate,
      description: entry.description,
      isAutoGenerated: entry.isAutoGenerated,
      lines: entry.lines.map((line: any) => ({
        id: line.id,
        ledgerId: line.ledgerId,
        ledger: {
          id: line.ledger.id,
          name: line.ledger.name
        },
        debit: line.debit ? line.debit.toString() : null,
        credit: line.credit ? line.credit.toString() : null
      })),
      totalDebit: totalDebit.toFixed(2),
      totalCredit: totalCredit.toFixed(2),
      isBalanced,
      createdAt: entry.createdAt
    };
  }

  private mapToLedgerResponse(ledger: LedgerWithCount): LedgerResponse {
    return {
      id: ledger.id,
      name: ledger.name,
      organizationId: ledger.organizationId,
      createdAt: ledger.createdAt,
      _count: {
        journalLines: ledger._count.journalLines
      }
    };
  }

  private mapToLedgerDetailResponse(ledger: LedgerWithLines): LedgerDetailResponse {
    let totalDebit = 0;
    let totalCredit = 0;

    const journalLines: JournalLineResponse[] = ledger.journalLines.map((line: any) => {
      totalDebit += parseFloat(line.debit?.toString() || '0');
      totalCredit += parseFloat(line.credit?.toString() || '0');
      return {
        id: line.id,
        ledgerId: line.ledgerId,
        ledger: {
          id: ledger.id,
          name: ledger.name
        },
        debit: line.debit ? line.debit.toString() : null,
        credit: line.credit ? line.credit.toString() : null
      };
    });

    return {
      id: ledger.id,
      name: ledger.name,
      organizationId: ledger.organizationId,
      createdAt: ledger.createdAt,
      _count: {
        journalLines: ledger._count.journalLines
      },
      journalLines,
      totalDebit: totalDebit.toFixed(2),
      totalCredit: totalCredit.toFixed(2)
    };
  }

  async createDefaultLedgers(clientId: string, organizationId: string): Promise<void> {
    await ledgerRepository.createDefaultLedgers(clientId, organizationId, DEFAULT_LEDGER_NAMES);
  }

  async listLedgers(
    clientId: string,
    filters: LedgerFilters
  ): Promise<PaginatedResponse<LedgerResponse>> {
    const { ledgers, total } = await ledgerRepository.findLedgersByClient(clientId, filters);
    const limit = filters.limit || 20;
    const page = filters.page || 1;

    return {
      data: ledgers.map(l => this.mapToLedgerResponse(l)),
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit)
      }
    };
  }

  async createLedger(
    clientId: string,
    organizationId: string,
    userId: string,
    input: CreateLedgerInput
  ): Promise<LedgerResponse> {
    const existing = await ledgerRepository.findLedgerByNameAndClient(input.name, clientId);
    if (existing) {
      throw new ConflictError('A ledger with this name already exists for this client');
    }

    const ledger = await ledgerRepository.createLedger({
      name: input.name,
      clientId,
      organizationId
    });

    await ledgerRepository.createAuditLog({
      userId,
      action: 'CREATE_LEDGER',
      resource: 'LEDGER',
      details: { ledgerId: ledger.id, name: ledger.name, clientId }
    });

    return {
      id: ledger.id,
      name: ledger.name,
      organizationId: ledger.organizationId,
      createdAt: ledger.createdAt,
      _count: { journalLines: 0 }
    };
  }

  async getLedgerById(
    ledgerId: string,
    clientId: string
  ): Promise<LedgerDetailResponse> {
    const ledger = await ledgerRepository.findLedgerByIdAndClient(ledgerId, clientId);
    if (!ledger) {
      throw new NotFoundError('Ledger');
    }
    return this.mapToLedgerDetailResponse(ledger);
  }

  async updateLedger(
    ledgerId: string,
    clientId: string,
    userId: string,
    input: UpdateLedgerInput
  ): Promise<LedgerResponse> {
    const ledger = await ledgerRepository.findLedgerByIdAndClient(ledgerId, clientId);
    if (!ledger) {
      throw new NotFoundError('Ledger');
    }

    if (input.name && input.name !== ledger.name) {
      const existing = await ledgerRepository.findLedgerByNameAndClient(input.name, clientId);
      if (existing) {
        throw new ConflictError('A ledger with this name already exists for this client');
      }
    }

    const updated = await ledgerRepository.updateLedger(ledgerId, clientId, input);

    await ledgerRepository.createAuditLog({
      userId,
      action: 'UPDATE_LEDGER',
      resource: 'LEDGER',
      details: { ledgerId, oldName: ledger.name, newName: input.name, clientId }
    });

    return {
      id: updated.id,
      name: updated.name,
      organizationId: updated.organizationId,
      createdAt: updated.createdAt,
      _count: { journalLines: ledger._count.journalLines }
    };
  }

  async deleteLedger(
    ledgerId: string,
    clientId: string,
    userId: string
  ): Promise<void> {
    const ledger = await ledgerRepository.findLedgerByIdAndClient(ledgerId, clientId);
    if (!ledger) {
      throw new NotFoundError('Ledger');
    }

    const hasLines = await ledgerRepository.hasJournalLines(ledgerId);
    if (hasLines) {
      throw new UnprocessableError(
        'Cannot delete a ledger that has journal entries. ' +
        'Remove all journal entries first.'
      );
    }

    await ledgerRepository.deleteLedger(ledgerId, clientId);

    await ledgerRepository.createAuditLog({
      userId,
      action: 'DELETE_LEDGER',
      resource: 'LEDGER',
      details: { ledgerId, name: ledger.name, clientId }
    });
  }

  async getLedgerBalanceSummary(
    clientId: string
  ): Promise<LedgerBalanceSummary[]> {
    const summary = await ledgerRepository.getLedgerBalanceSummary(clientId);

    return summary.map(row => {
      const totalDebit = parseFloat(row.totalDebit?.toString() || '0');
      const totalCredit = parseFloat(row.totalCredit?.toString() || '0');
      const netBalance = totalDebit - totalCredit;

      return {
        ledgerId: row.ledgerId,
        ledgerName: row.ledgerName,
        totalDebit: totalDebit.toFixed(2),
        totalCredit: totalCredit.toFixed(2),
        netBalance: netBalance.toFixed(2)
      };
    });
  }

  async createAutoJournalEntry(
    invoice: InvoiceWithAll,
    organizationId: string
  ): Promise<void> {
    try {
      const clientId = invoice.clientId;
      if (!clientId) {
        logger.warn({ invoiceId: invoice.id }, 'Invoice has no client assigned. Auto journal entry skipped.');
        return;
      }

      const totalAmountNum = parseFloat(invoice.totalAmount?.toString() || '0');
      const gstAmountNum = parseFloat(invoice.gstAmount?.toString() || '0');
      const cgstAmountNum = parseFloat(invoice.cgstAmount?.toString() || '0');
      const sgstAmountNum = parseFloat(invoice.sgstAmount?.toString() || '0');
      const igstAmountNum = parseFloat(invoice.igstAmount?.toString() || '0');

      if (totalAmountNum <= 0) {
        logger.warn({ invoiceId: invoice.id }, 'Total amount is zero or missing. Auto journal entry skipped.');
        return;
      }

      const requiredLedgerNames = [
        'Purchase Account',
        'Input GST - CGST',
        'Input GST - SGST',
        'Input GST - IGST',
        'Accounts Payable'
      ];

      const ledgers = await ledgerRepository.findLedgersByNames(requiredLedgerNames, clientId);
      const ledgerMap = new Map<string, string>();
      for (const l of ledgers) {
        ledgerMap.set(l.name, l.id);
      }

      const purchaseLedgerId = ledgerMap.get('Purchase Account');
      const payableLedgerId = ledgerMap.get('Accounts Payable');

      if (!purchaseLedgerId || !payableLedgerId) {
        logger.warn({ invoiceId: invoice.id, clientId }, 'Missing basic ledgers (Purchase Account or Accounts Payable) for client.');
        await ledgerRepository.createAuditLog({
          action: 'AUTO_JOURNAL_SKIPPED',
          resource: 'INVOICE',
          details: { invoiceId: invoice.id, clientId, reason: 'Missing basic ledgers for client.' }
        });
        return;
      }

      const baseAmount = totalAmountNum - gstAmountNum;
      const lines: CreateJournalLineInput[] = [];

      lines.push({ ledgerId: purchaseLedgerId, debit: baseAmount });
      lines.push({ ledgerId: payableLedgerId, credit: totalAmountNum });

      const cgstLedgerId = ledgerMap.get('Input GST - CGST');
      if (cgstAmountNum > 0 && cgstLedgerId) {
        lines.push({ ledgerId: cgstLedgerId, debit: cgstAmountNum });
      }

      const sgstLedgerId = ledgerMap.get('Input GST - SGST');
      if (sgstAmountNum > 0 && sgstLedgerId) {
        lines.push({ ledgerId: sgstLedgerId, debit: sgstAmountNum });
      }

      const igstLedgerId = ledgerMap.get('Input GST - IGST');
      if (igstAmountNum > 0 && igstLedgerId) {
        lines.push({ ledgerId: igstLedgerId, debit: igstAmountNum });
      }

      const { isBalanced } = this.calculateTotals(lines);
      if (!isBalanced) {
        logger.warn({ invoiceId: invoice.id, amounts: { totalAmountNum, gstAmountNum } }, 'Unbalanced auto amounts.');
        await ledgerRepository.createAuditLog({
          action: 'AUTO_JOURNAL_BALANCE_ERROR',
          resource: 'INVOICE',
          details: { invoiceId: invoice.id, lines, clientId }
        });
        return;
      }

      await ledgerRepository.createJournalEntry({
        invoiceId: invoice.id,
        entryDate: invoice.approvedAt || new Date(),
        description: `Auto journal entry for invoice ${invoice.invoiceNumber}`,
        isAutoGenerated: true,
        lines
      });

      await ledgerRepository.createAuditLog({
        action: 'AUTO_JOURNAL_CREATED',
        resource: 'INVOICE',
        details: { invoiceId: invoice.id, lineCount: lines.length, clientId }
      });

    } catch (error) {
      logger.error({ error, invoiceId: invoice.id }, 'Auto journal entry creation failed');
    }
  }

  async listJournalEntries(
    clientId: string,
    filters: JournalEntryFilters
  ): Promise<PaginatedResponse<JournalEntryResponse>> {
    const { entries, total } = await ledgerRepository.findJournalEntriesByClient(clientId, filters);
    const limit = filters.limit || 20;
    const page = filters.page || 1;

    return {
      data: entries.map(e => this.mapToJournalEntryResponse(e)),
      meta: {
        total,
        page,
        limit,
        totalPages: Math.ceil(total / limit)
      }
    };
  }

  async getJournalEntry(
    journalEntryId: string,
    clientId: string
  ): Promise<JournalEntryResponse> {
    const entry = await ledgerRepository.findJournalEntryById(journalEntryId, clientId);
    if (!entry) {
      throw new NotFoundError('Journal entry');
    }
    return this.mapToJournalEntryResponse(entry);
  }

  async getInvoiceJournalEntries(
    invoiceId: string,
    organizationId: string,
    clientId?: string
  ): Promise<JournalEntryResponse[]> {
    const invoice = await invoicesRepository.findInvoiceByIdAndOrg(invoiceId, organizationId);
    if (!invoice) {
      throw new NotFoundError('Invoice');
    }

    if (clientId && invoice.clientId !== clientId) {
      throw new UnprocessableError('Invoice does not belong to the specified client');
    }

    if (!invoice.clientId) {
      return [];
    }

    const entries = await ledgerRepository.findJournalEntriesByInvoice(invoiceId, invoice.clientId);
    return entries.map(e => this.mapToJournalEntryResponse(e));
  }

  async createJournalEntry(
    clientId: string,
    organizationId: string,
    userId: string,
    input: CreateJournalEntryInput
  ): Promise<JournalEntryResponse> {
    const invoice = await invoicesRepository.findInvoiceByIdAndOrg(input.invoiceId, organizationId);
    if (!invoice) {
      throw new NotFoundError('Invoice');
    }

    if (invoice.clientId !== clientId) {
      throw new UnprocessableError('Invoice does not belong to the specified client');
    }

    if (invoice.status !== InvoiceStatus.APPROVED) {
      throw new UnprocessableError('Journal entries can only be created for APPROVED invoices.');
    }

    const { isBalanced } = this.calculateTotals(input.lines);
    if (!isBalanced) {
      throw new UnprocessableError('Journal entry is not balanced. Total debits must equal total credits.');
    }

    // Validate ledgers belong to client
    const ledgerIds = input.lines.map(line => line.ledgerId);
    const uniqueLedgerIds = [...new Set(ledgerIds)];
    for (const lid of uniqueLedgerIds) {
      const ledger = await ledgerRepository.findLedgerByIdAndClient(lid, clientId);
      if (!ledger) {
        throw new NotFoundError('Ledger');
      }
    }

    const entry = await ledgerRepository.createJournalEntry({
      invoiceId: input.invoiceId,
      entryDate: new Date(input.entryDate),
      description: input.description,
      isAutoGenerated: false,
      lines: input.lines
    });

    await ledgerRepository.createAuditLog({
      userId,
      action: 'CREATE_JOURNAL_ENTRY',
      resource: 'JOURNAL_ENTRY',
      details: { journalEntryId: entry.id, invoiceId: entry.invoiceId, lineCount: input.lines.length, clientId }
    });

    return this.mapToJournalEntryResponse(entry);
  }

  async deleteJournalEntry(
    journalEntryId: string,
    clientId: string,
    userId: string
  ): Promise<void> {
    const entry = await ledgerRepository.findJournalEntryById(journalEntryId, clientId);
    if (!entry) {
      throw new NotFoundError('Journal entry');
    }

    if (entry.isAutoGenerated) {
      throw new UnprocessableError('Auto-generated journal entries cannot be deleted. Reopen the invoice to regenerate them.');
    }

    if (entry.invoice.syncStatus === 'SYNCED') {
      throw new UnprocessableError('Cannot delete journal entry for an invoice that has been exported to Tally. Reset sync status first.');
    }

    await ledgerRepository.deleteJournalEntry(journalEntryId, clientId);

    await ledgerRepository.createAuditLog({
      userId,
      action: 'DELETE_JOURNAL_ENTRY',
      resource: 'JOURNAL_ENTRY',
      details: { journalEntryId, invoiceId: entry.invoiceId, clientId }
    });
  }
}

export const ledgerService = new LedgerService();
