/*
  Warnings:

  - A unique constraint covering the columns `[organizationId,name]` on the table `Ledger` will be added. If there are existing duplicate values, this will fail.

*/
-- AlterTable
ALTER TABLE "JournalEntry" ADD COLUMN     "isAutoGenerated" BOOLEAN NOT NULL DEFAULT true;

-- CreateIndex
CREATE UNIQUE INDEX "Ledger_organizationId_name_key" ON "Ledger"("organizationId", "name");
