export const Permissions = {
  // Invoice
  CREATE_INVOICE: 'CREATE_INVOICE',
  EDIT_INVOICE: 'EDIT_INVOICE',
  DELETE_INVOICE: 'DELETE_INVOICE',
  SUBMIT_INVOICE: 'SUBMIT_INVOICE',
  APPROVE_INVOICE: 'APPROVE_INVOICE',
  REJECT_INVOICE: 'REJECT_INVOICE',
  REOPEN_INVOICE: 'REOPEN_INVOICE',
  REPROCESS_INVOICE: 'REPROCESS_INVOICE',
  EXPORT_INVOICE: 'EXPORT_INVOICE',

  // Document
  UPLOAD_DOCUMENT: 'UPLOAD_DOCUMENT',
  DELETE_DOCUMENT: 'DELETE_DOCUMENT',

  // Client
  CREATE_CLIENT: 'CREATE_CLIENT',
  EDIT_CLIENT: 'EDIT_CLIENT',
  DELETE_CLIENT: 'DELETE_CLIENT',

  // Users
  MANAGE_USERS: 'MANAGE_USERS',

  // Organization
  MANAGE_ORG: 'MANAGE_ORG',
  VIEW_AUDIT_LOGS: 'VIEW_AUDIT_LOGS',

  // Ledger
  MANAGE_LEDGER: 'MANAGE_LEDGER',
  MANAGE_JOURNAL: 'MANAGE_JOURNAL',

  // Billing
  MANAGE_BILLING: 'MANAGE_BILLING',

  // Reports
  VIEW_DASHBOARD: 'VIEW_DASHBOARD',
  VIEW_REPORTS: 'VIEW_REPORTS',

} as const;

export type PermissionType = typeof Permissions[keyof typeof Permissions];